;/*FB_PKG_DELIM*/

__d("PolarisClipsAudioRoot.entrypoint",["JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{}}},root:c("JSResourceForInteraction")("PolarisClipsAudioRoot.react").__setRef("PolarisClipsAudioRoot.entrypoint")};g["default"]=a}),98);
__d("PolarisDesktopPostPageRelatedMediaGridQuery_instagramRelayOperation",[],(function(a,b,c,d,e,f){e.exports="8875247669163844"}),null);
__d("PolarisDesktopPostPageRelatedMediaGridQuery$Parameters",["PolarisDesktopPostPageRelatedMediaGridQuery_instagramRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PolarisDesktopPostPageRelatedMediaGridQuery_instagramRelayOperation"),metadata:{is_distillery:!0},name:"PolarisDesktopPostPageRelatedMediaGridQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PolarisPostCommentsContainerQuery_instagramRelayOperation",[],(function(a,b,c,d,e,f){e.exports="8527751017247078"}),null);
__d("PolarisPostCommentsContainerQuery$Parameters",["PolarisIsLoggedIn.relayprovider","PolarisPostCommentsContainerQuery_instagramRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PolarisPostCommentsContainerQuery_instagramRelayOperation"),metadata:{is_distillery:!0},name:"PolarisPostCommentsContainerQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__PolarisIsLoggedInrelayprovider:b("PolarisIsLoggedIn.relayprovider")}}};e.exports=a}),null);
__d("PolarisPostRootQuery$Parameters",["PolarisFeedShareMenu.relayprovider","PolarisIsLoggedIn.relayprovider","PolarisPostRootQuery_instagramRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PolarisPostRootQuery_instagramRelayOperation"),metadata:{is_distillery:!0},name:"PolarisPostRootQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__PolarisFeedShareMenurelayprovider:b("PolarisFeedShareMenu.relayprovider"),__relay_internal__pv__PolarisIsLoggedInrelayprovider:b("PolarisIsLoggedIn.relayprovider")}}};e.exports=a}),null);
__d("PolarisDesktopPostRoot.entrypoint",["JSResourceForInteraction","PolarisDesktopPostPageRelatedMediaGridQuery$Parameters","PolarisPostCommentsContainerQuery$Parameters","PolarisPostRootQuery$Parameters","gkx"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){var b=a.routeParams.shortcode;a=a.routeProps;var d=a.media_id;a=a.media_owner_id;return{queries:{polarisCommentsQuery:{options:{},parameters:c("PolarisPostCommentsContainerQuery$Parameters"),variables:{media_id:d}},polarisPostRootQuery:{options:{},parameters:c("PolarisPostRootQuery$Parameters"),variables:{shortcode:b}},polarisRelatedMediaQuery:{options:{},parameters:c("PolarisDesktopPostPageRelatedMediaGridQuery$Parameters"),variables:{count:c("gkx")("1878")?7:null,media_owner_id:a}}}}},root:c("JSResourceForInteraction")("PolarisDesktopPostRoot.react").__setRef("PolarisDesktopPostRoot.entrypoint")};g["default"]=a}),98);
__d("usePolarisFeedVariantFromRoute",["CometRouteParams","PolarisFeedVariants","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";function a(){var a=d("react-compiler-runtime").c(2),b=d("CometRouteParams").useRouteParams();b=b.variant;if(a[0]!==b){var e;e=(e=c("PolarisFeedVariants").cast(String(b)))!=null?e:"home";a[0]=b;a[1]=e}else e=a[1];return e}g["default"]=a}),98);
__d("PolarisFeedContext.react",["PolarisFeedTypes","emptyFunction","react","react-compiler-runtime","usePolarisFeedVariantFromRoute"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));b=h;b.useMemo;var j=b.useRef,k=b.useState;function l(a,b){switch(a){case"past_posts":return d("PolarisFeedTypes").PaginationSource.PAST_POSTS;case"favorites":return d("PolarisFeedTypes").PaginationSource.FAVORITES;case"following":return d("PolarisFeedTypes").PaginationSource.FOLLOWING;case"home":return b?d("PolarisFeedTypes").PaginationSource.FEED_RECS:null}}var m=i.createContext({feedContainerWidth:null,feedMediaWidth:null,paginationSource:null,seenLoggedOutFeedItems:{current:new Set()},setShowEmptyFeed:c("emptyFunction"),setShowEOFRecs:c("emptyFunction"),showEmptyFeed:!1});function a(a){var b=d("react-compiler-runtime").c(13),e=a.children,f=a.feedContainerWidth,g=a.feedMediaWidth,h=a.setShowEmptyFeed;a=a.showEmptyFeed;var n=k(!1),o=n[0];n=n[1];var p;b[0]===Symbol["for"]("react.memo_cache_sentinel")?(p=new Set(),b[0]=p):p=b[0];p=j(p);var q=c("usePolarisFeedVariantFromRoute")(),r;b[1]!==o||b[2]!==q?(r=l(q,o),b[1]=o,b[2]=q,b[3]=r):r=b[3];o=r;b[4]!==f||b[5]!==g||b[6]!==o||b[7]!==h||b[8]!==a?(q={feedContainerWidth:f,feedMediaWidth:g,paginationSource:o,seenLoggedOutFeedItems:p,setShowEmptyFeed:h,setShowEOFRecs:n,showEmptyFeed:a},b[4]=f,b[5]=g,b[6]=o,b[7]=h,b[8]=a,b[9]=q):q=b[9];r=q;p=r;b[10]!==e||b[11]!==p?(n=i.jsx(m.Provider,{value:p,children:e}),b[10]=e,b[11]=p,b[12]=n):n=b[12];return n}g.getPaginationSourceFromVariant=l;g.PolarisFeedContext=m;g.PolarisFeedContextProvider=a}),98);
__d("PolarisMobileAllCommentsPageQuery_instagramRelayOperation",[],(function(a,b,c,d,e,f){e.exports="26984700841143449"}),null);
__d("PolarisMobileAllCommentsPageQuery$Parameters",["PolarisMobileAllCommentsPageQuery_instagramRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PolarisMobileAllCommentsPageQuery_instagramRelayOperation"),metadata:{is_distillery:!0},name:"PolarisMobileAllCommentsPageQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PolarisMobileAllCommentsRootNext.entrypoint",["JSResourceForInteraction","PolarisMobileAllCommentsPageQuery$Parameters","PolarisPostCommentsContainerQuery$Parameters"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.routeProps.media_id;return{queries:{commentsQuery:{options:{},parameters:c("PolarisPostCommentsContainerQuery$Parameters"),variables:{media_id:a}},mediaQuery:{options:{},parameters:c("PolarisMobileAllCommentsPageQuery$Parameters"),variables:{media_id:a}}}}},root:c("JSResourceForInteraction")("PolarisMobileAllCommentsRoot.next.react").__setRef("PolarisMobileAllCommentsRootNext.entrypoint")};g["default"]=a}),98);
__d("PolarisMobileLikedByRoot.entrypoint",["JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{}}},root:c("JSResourceForInteraction")("PolarisMobileLikedByRoot.react").__setRef("PolarisMobileLikedByRoot.entrypoint")};g["default"]=a}),98);
__d("PolarisMobilePostPageHeader.next.react",["fbt","PolarisGenericMobileHeader.react","PolarisMobileHeaderWrapper.react","PolarisNavBackButton.react","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g,h){"use strict";var i,j=i||d("react"),k=h._(/*BTDS*/"__JHASH__tsG71JEKkVB__JHASH__");function a(){var a=d("react-compiler-runtime").c(1);if(a[0]===Symbol["for"]("react.memo_cache_sentinel")){var b=[j.jsx(c("PolarisNavBackButton.react"),{analyticsContext:"postPage"},"back")];b=j.jsx(c("PolarisGenericMobileHeader.react"),{leftActions:b,title:k});b=j.jsx(c("PolarisMobileHeaderWrapper.react"),{children:b});a[0]=b}else b=a[0];return b}g["default"]=a}),226);
__d("usePolarisGetFeedMediaWidthBasedOnReelHeight",["PolarisFeedPageConstants"],(function(a,b,c,d,e,f,g){"use strict";function a(){return"min("+d("PolarisFeedPageConstants").FAMILIAR_FEED_WIDTH+"px, 100vw)"}g["default"]=a}),98);
__d("usePolarisGetFeedContainerWidth",["PolarisFeedPageConstants","PolarisIsUsingStoryTrayPrism","PolarisUA","usePolarisGetFeedMediaWidthBasedOnReelHeight"],(function(a,b,c,d,e,f,g){"use strict";function a(){var a=c("usePolarisGetFeedMediaWidthBasedOnReelHeight")(),b=d("PolarisIsUsingStoryTrayPrism").isUsingStoryTrayPrism()?d("PolarisFeedPageConstants").FEED_WIDTH_WIDE_STORY_PRISM:d("PolarisFeedPageConstants").FEED_WIDTH_WIDE_STORY;return d("PolarisUA").isDesktop()?b+"px":a+"px"}g["default"]=a}),98);